### PR TITLE
Add max-count and skip params for commits method

### LINKED ISSUE #15: commits method should allow max-count and skip as parameters
The `commits` method currently tries to pull in all the commits of a repository since inception. This is very infeasible if the repository is very large, like the [Linux repository](https://github.com/torvalds/linux). The methods relies on the underlying git command `rev-list`, which takes parameters `max-count` and `skip`. Implementing these into the library would be beneficial for applications that only want the first 100 commits instead of 700, 000.

### PR DESCRIPTION
**Pull request by ryanleecode**
Fixes #15

### CODE REVIEW

**Comment by kevmoo** [comment]
looks like you need to fix formatting!

**Comment by kevmoo** [comment]
please rebase if you'd like to keep running w/ this!

**Comment by ryanleecode** [comment]
ack

**Comment by ryanleecode** [comment]
Formatted and rebased. Feel free to squash and merge.

**Comment by kevmoo** [comment]
@ryanleecode – still care about this?

**Comment by ryanleecode** [comment]
> @ryanleecode – still care about this?

I barely remembered this existed :smile: . You can close or merge if you want.

**Pull request closed without merging**
