### PR TITLE
[WIP] feat: diff

### PR DESCRIPTION
**Pull request by jenshor**
### About this PR

This PR implements a rather rudimental [`git diff`](https://git-scm.com/docs/git-diff) command. While this is not really production ready yet, we'd like to create a CLI in beta which depends on these changes. I'm opening this draft PR to check which feature set is required to get something merged and published to pub.dev. 

I'm happy to implement `git diff` properly in the future, but this conflicts with our current internal roadmap. However, maybe I can improve this PR to something that is merge worthy but not the full feature set in less time. 

### What's already working (but not really tested)

- `git diff` returns which files changed between two commits or branches `base` and `ref`
- `FileDiff`s indicates the following changes in a file 
    - New file: didn't exist in `base` and was created in `ref`
    - Changed file: exists in `base` and `ref` but some lines changed
    - Deleted file: existed in `base` but was removed in `ref`
    - `DiffHunk`: the hunks which changed (basically line diff)

### Requirements for our team 
- Tests

### Requirements to get `git diff` merged and published to pub.dev
- to be discussed

Thanks for this amazing package 🚀
Let me know what's required to get this merged and published.

### CODE REVIEW

**Comment by kevmoo** [comment]
@jenshor – still care about this?

**Comment by jenshor** [comment]
Yes. We'd like to get this merged, if possible. Let me know what you need 👍🏻

**Comment by kevmoo** [comment]
You need to rebase, to start with! – so we can run tests

**Comment by kevmoo** [comment]
please rebase – or I can just close it out and you can come back later?

**Comment by jenshor** [comment]
Let's close it for now and I'll come back later. Thanks for your efforts 👍🏻

**Pull request closed without merging**
